#!/bin/bash
# Keep the Codex side of this machine pointing at the Claude side, with ONE writer per target.
#
# The native importer (ChatGPT desktop -> Settings -> Import, "automatic updates") is the other
# writer, and what it produces is not usable as-is: it rewrites the text of every file it copies,
# case-insensitively replacing "claude" with "Codex". Measured 5.9.2026 over the 13 skills it had
# just written, that turned ~/.claude/scripts/<x> into ~/.Codex/scripts/<x>
# (a directory that does not exist), claude-usage.sh into Codex-usage.sh (measured 5.9.2026: no
# such file in ~/.claude/scripts), and the teardown pattern */.claude/worktrees/* into
# */.Codex/worktrees/*,
# which matches nothing and so reports a clean teardown over untouched directories.
#
# It also skips anything already present: the four skills and both AGENTS.md files it had written
# in July were left untouched by the sync that ran at 20:41 on 5.9.2026, while 13 new skills
# appeared with that timestamp. So a target this script owns stays owned — and --check exists to
# notice the day that stops being true.
#
# Owned targets (nothing else is written):
#   ~/.codex/AGENTS.md              generated: AGENTS.codex.md + ~/.claude/CLAUDE.md
#   ~/AGENTS.md                     stub pointing at the real one (measured: not loaded by Codex,
#                                   but present so the importer does not recreate a rewritten copy)
#   ~/.agents/skills/<name>         a symlink HERE, pointing at the real directory in ~/.claude/skills
#   ~/.codex/hooks/<name>.sh        a symlink HERE, pointing at the real script in ~/.claude/hooks
#   ~/.codex/AGENTS.codex.md        a symlink HERE -> codex/AGENTS.codex.md
#   ~/.codex/hooks.json             a symlink HERE -> codex/hooks.json, which is RENDERED from
#                                   codex/hooks.template.json (__CODEX_HOME__ -> the real path;
#                                   Codex wants absolute hook paths, the repo must not carry one)
#   ~/.codex/rules/<name>.rules     a symlink HERE per codex/rules/*.rules (default.rules is the
#                                   generic layer, local.rules the machine-specific one; Codex
#                                   scans every *.rules file in the directory)
#   ~/AGENTS.md                     a symlink HERE -> codex/home-AGENTS.md (content written below)
#   ~/.codex/safe-bin/*             a COPY from codex/safe-bin — see the note at that check
#
# Not owned, deliberately: ~/.codex/config.toml and the Agy settings files are written by their
# own apps (config.toml changed three times during one session on 5.9.2026), so a stored copy
# would conflict forever and rot. Their authored parts are ASSERTED instead, and the repo keeps a
# restore copy of the Agy files, which is compared and not written back.
#
# The source of truth is ~/.claude in both cases. That side is a git repo, so the history and the
# fixture suite live with the files; the importer writes into ~/.agents/skills and ~/.codex and
# left ~/.claude untouched in the sync measured on 5.9.2026; and the Codex permission profile
# grants ~/.codex read access alone, which would fence off the files edited most often.
#
# Usage:
#   codex-sync.sh --render-plist   print the LaunchAgent plist for THIS home (from codex/codex-sync.plist.template)
#   codex-sync.sh --check     report drift, write the JSON report, exit 1 if anything is off
#   codex-sync.sh --dry-run   print what --apply would change, change nothing
#   codex-sync.sh --apply     make it so (backs up any file it replaces)
#   codex-sync.sh --tests     also run the hook fixture suite

set -uo pipefail

# Every root is overridable so the fixture suite (scripts/tests/test-codex-sync.sh) can drive this
# script against a throwaway tree. Defaults are the real thing; nothing else reads these vars.
: "${CS_HOME:=$HOME}"
: "${CLAUDE_HOME:=$CS_HOME/.claude}"
: "${CODEX_HOME:=$CS_HOME/.codex}"
: "${AGENTS_DIR:=$CS_HOME/.agents}"
: "${BACKUP_DIR:=$CLAUDE_HOME/backups/codex-sync}"
: "${REPORT:=$CLAUDE_HOME/cache/codex-sync-report.json}"
: "${LOCK:=$CLAUDE_HOME/cache/codex-sync.lock}"   # user-owned dir, not the shared /tmp (a pre-created symlink there would be followed)
: "${CS_NOTIFY:=1}"
# Read the delta from the REPO, not through the ~/.codex symlink that points at it: on a fresh
# machine that symlink does not exist yet, and this section runs before the one that creates it.
# Taking it from the outlet made --apply report "missing source" on exactly the machine the whole
# arrangement exists to set up (caught by scripts/tests/test-codex-sync.sh, 5.9.2026).
DELTA="$CLAUDE_HOME/codex/AGENTS.codex.md"
RULEBOOK="$CLAUDE_HOME/CLAUDE.md"
TARGET="$CODEX_HOME/AGENTS.md"
STUB="$CS_HOME/AGENTS.md"
MARKER="<!-- generated by ~/.claude/scripts/codex-sync.sh — do not edit; see AGENTS.codex.md -->"

MODE="${1:---check}"
# --dry-run is an alias for --check. Both take the same inspecting pass; the DRIFT lines they
# print name what --apply would repair. Writes happen under --apply (see the MODE tests below).
[ "$MODE" = "--dry-run" ] && MODE="--check"
RUN_TESTS=0
[ "${2:-}" = "--tests" ] && RUN_TESTS=1
[ "$MODE" = "--tests" ] && { MODE="--check"; RUN_TESTS=1; }

# Three outcomes, not two. A repair that could not be made is NOT drift that was handled, and
# reporting it as one is how --apply came to print "repaired" and exit 0 after refusing to write
# (found by a Codex review 5.9.2026, reproduced in scripts/tests/test-codex-sync.sh).
drift=()          # what the inspecting pass found
repaired=()       # what --apply actually changed, verified after the write
failed=()         # what could not be repaired, or must not be
note()   { drift+=("$1"); echo "  DRIFT  $1"; }
# Findings inside a project checkout. This script does not write in a repo, which a fixture
# pins by comparing the project HEAD across an --apply run. A shared checkout
# can hold another session's uncommitted work and an unpushed commit, and on 5.9.2026 it held
# both. So they are reported and counted as drift for --check, but --apply neither repairs nor
# notifies about them — an hourly notification nobody can act on becomes an hourly notification
# nobody reads.
advisory=()
advise() { advisory+=("$1"); echo "  NEEDS A HUMAN  $1"; }
ok()     { echo "  ok     $1"; }
did()    { repaired+=("$1"); echo "  FIXED    $1"; }
cannot() { failed+=("$1"); echo "  FAILED   $1" >&2; }

# Machine-specific values for the templates (a plist label, the GitHub owner the push wrapper
# accepts, the projects directory). Read from codex/local.env when it exists — that file is
# private and not exported; codex/local.env.example documents the keys.
CS_LOCAL_ENV="$CLAUDE_HOME/codex/local.env"
# shellcheck disable=SC1090
[ -f "$CS_LOCAL_ENV" ] && . "$CS_LOCAL_ENV"
: "${CS_USER:=$(id -un)}"
: "${CS_PROJECTS_DIR:=$CS_HOME/Projects}"
: "${CS_GITHUB_OWNER:=}"
: "${CS_LAUNCH_LABEL:=local.one-rulebook.codex-sync}"
# render_tpl <template-file>: the template with every placeholder substituted, on stdout.
# Literal replacement in Python, not sed: a value carrying the sed delimiter broke the substitution
# and the failure was MASKED — sed printed nothing, rc stayed 0, and --apply would have written the
# empty rendering over hooks.json (reproduced 20.9.2026 with CS_HOME='/tmp/a|b'; found by review).
# Fail-closed: non-zero and no output on any failure, including an empty rendering.
render_tpl() {
  local out
  out=$(python3 - "$1" "$CS_HOME" "$CODEX_HOME" "$CS_USER" "$CS_PROJECTS_DIR" "$CS_GITHUB_OWNER" "$CS_LAUNCH_LABEL" <<'PY'
import sys
tpl, *vals = sys.argv[1:]
keys = ("__HOME__", "__CODEX_HOME__", "__USER__", "__PROJECTS__", "__GITHUB_OWNER__", "__LABEL__")
if tpl.endswith(".plist.template"):
    import html
    vals = [html.escape(v, quote=True) for v in vals]   # a & or < in a path must not break the XML
try:
    text = open(tpl, encoding="utf-8").read()
except OSError as e:
    sys.exit(f"render_tpl: {e}")
for k, v in zip(keys, vals):
    text = text.replace(k, v)
if not text.strip():
    sys.exit("render_tpl: empty rendering")
sys.stdout.write(text)
PY
  ) || { echo "  FAILED   render_tpl $1" >&2; return 1; }
  [ -n "$out" ] || return 1
  printf '%s\n' "$out"
}
# sha256 of stdin, for comparing a rendering with a file without holding both in shell variables
sha256_stream() { if command -v shasum >/dev/null 2>&1; then shasum -a 256; else sha256sum; fi | cut -d" " -f1; }

# --render-plist: print the LaunchAgent plist for this home and stop. No inspecting pass, no
# lock, no report — the caller redirects it into ~/Library/LaunchAgents and bootstraps it.
if [ "$MODE" = "--render-plist" ]; then
  TPL="$CLAUDE_HOME/codex/codex-sync.plist.template"
  [ -f "$TPL" ] || { echo "error: $TPL missing" >&2; exit 1; }
  render_tpl "$TPL" || exit 1
  exit 0
fi

# Portability: this script also runs on Linux (no shasum, no osascript), where the same arrangement
# keeps that machine's Codex pointing at that machine's ~/.claude.
sha256() { if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1"; else sha256sum "$1"; fi | cut -d" " -f1; }
notify() { # notify <title> <message> — a desktop notification on macOS, a syslog line elsewhere
  [ "$CS_NOTIFY" = "1" ] || return 0
  if [ -x /usr/bin/osascript ]; then /usr/bin/osascript -e "display notification \"$2\" with title \"$1\"" 2>/dev/null
  else logger -t codex-sync "$1: $2" 2>/dev/null; fi
  return 0
}

# ---- single writer at a time -------------------------------------------------------------------
# An OS advisory lock, because both hand-rolled protocols before it had a window. The pid file was
# truncated by the redirection that opened it; the mkdir version created the directory and wrote
# the pid in two steps, so a second run arriving in between read no pid, called the lock orphaned,
# removed it and went in — and the first run's EXIT trap then deleted the live second's lock
# (reproduced by a Codex review 5.9.2026).
#
# flock has no window and no bookkeeping: the kernel holds it against the open file description,
# so it needs no stale detection and is released when this process dies, however it dies.
# Measured 5.9.2026 on this Mac: the lock survives the python child that applies it (the parent's
# fd keeps the description open) and is released when the holder exits.
# ⚠️ A long-lived CHILD would inherit fd 9 and keep the lock alive after this script ends. Every
# child here is short-lived; anything backgrounded later must be started with 9<&-.
# ⚠️ No `2>/dev/null` on this line: `exec` with redirections alone applies them to the SHELL for
# the rest of the script, so the stderr redirect that used to sit here silenced every FAILED line
# after the lock was taken (reproduced 20.9.2026: a template that could not be rendered set rc=1
# and printed nothing). A failed open makes a non-interactive bash print its own error and exit.
mkdir -p "$(dirname "$LOCK")" 2>/dev/null   # a fresh install has no cache/ yet
exec 9<>"$LOCK"
if ! python3 -c 'import fcntl, sys
try:
    fcntl.flock(9, fcntl.LOCK_EX | fcntl.LOCK_NB)
except OSError:
    sys.exit(1)' 2>/dev/null; then
  echo "another codex-sync holds $LOCK" >&2; exit 3
fi
echo $$ > "$LOCK"   # diagnostics only; nothing reads it to make a decision

# A first --apply on a machine with no ~/.codex yet: the targets need their directories (the
# rendering below writes into $CODEX_HOME and safe-bin). --check creates nothing.
if [ "$MODE" = "--apply" ]; then
  mkdir -p "$CODEX_HOME" "$CODEX_HOME/hooks" "$CODEX_HOME/rules" "$CODEX_HOME/safe-bin" "$AGENTS_DIR/skills" 2>/dev/null \
    || { echo "error: cannot create the Codex target directories under $CODEX_HOME" >&2; exit 1; }
fi

backup() { # backup <path> — 0 only when a copy exists afterwards, or when there was nothing to copy
  [ -e "$1" ] || return 0
  mkdir -p "$BACKUP_DIR" 2>/dev/null || return 1
  local d="$BACKUP_DIR/$(basename "$1").$(date +%Y%m%d-%H%M%S).$$"
  cp -a "$1" "$d" 2>/dev/null || return 1
  [ -e "$d" ] || return 1
  return 0
}

# A target is replaced after its backup exists, not before. Until 5.9.2026 the caller ignored
# backup's status and ran rm -rf regardless; a fixture with an unusable backup directory lost a
# file that existed nowhere else.
replace_with_link() { # replace_with_link <target> <link destination> <label>
  if ! backup "$1"; then cannot "$3: backup failed, target left untouched"; return 1; fi
  rm -rf "$1"; mkdir -p "$(dirname "$1")"; ln -s "$2" "$1"
  if [ -L "$1" ] && [ -e "$1" ]; then did "$3"; return 0; fi
  cannot "$3: the link was not created"; return 1
}

render() { # the generated AGENTS.md, on stdout
  echo "$MARKER"
  echo
  cat "$DELTA"
  echo
  cat "$RULEBOOK"
}

# ---- 1. the generated global instructions ----------------------------------------------------
echo "── global instructions ──"
if [ ! -f "$DELTA" ] || [ ! -f "$RULEBOOK" ]; then
  cannot "missing source: $DELTA or $RULEBOOK"
else
  WANT=$(render)
  if [ ! -f "$TARGET" ]; then
    note "$TARGET is missing"
  elif [ "$(head -1 "$TARGET")" != "$MARKER" ]; then
    # Somebody else wrote this file. Report it instead of overwriting it — see the refusal below.
    note "$TARGET is NOT ours (no generator marker on line 1) — another writer has taken it"
  elif [ "$WANT" != "$(cat "$TARGET")" ]; then
    note "$TARGET is stale relative to CLAUDE.md / AGENTS.codex.md"
  else
    ok "$TARGET is current"
  fi

  # Write when it would change something. Rewriting a correct file on every run made
  # the hourly LaunchAgent report a repair it had not needed to make, and a notification with it.
  if [ "$MODE" = "--apply" ] && { [ ! -f "$TARGET" ] || [ "$WANT" != "$(cat "$TARGET")" ]; }; then
    if [ -f "$TARGET" ] && [ "$(head -1 "$TARGET")" != "$MARKER" ]; then
      cannot "$TARGET carries no generator marker — refusing to overwrite it. Move it aside first."
    elif ! backup "$TARGET"; then
      cannot "$TARGET: backup failed, not rewritten"
    else
      TMP=$(mktemp "$CODEX_HOME/.AGENTS.md.XXXXXX")
      if render > "$TMP" && mv -f "$TMP" "$TARGET" && [ "$(cat "$TARGET")" = "$WANT" ]; then
        did "$TARGET rewritten ($(wc -c <"$TARGET" | tr -d " ") B)"
      else
        rm -f "$TMP"; cannot "$TARGET could not be written"
      fi
    fi
  fi
fi

# ---- 2. the ~/AGENTS.md stub ------------------------------------------------------------------
STUB_TEXT="# Global instructions

Codex loads its global instructions from \`~/.codex/AGENTS.md\`, not from this file — measured
5.9.2026 with \`codex debug prompt-input\` from three working directories, where a marker added
here never reached the model and a marker in \`~/.codex/AGENTS.md\` always did.

This stub exists so the importer does not recreate a full, path-rewritten copy in its place.
Edit \`~/.codex/AGENTS.codex.md\` or \`~/.claude/CLAUDE.md\` instead."

# The stub's content belongs in the REPO file; ~/AGENTS.md is the outlet symlink that
# section 4b creates. Writing the text straight into ~/AGENTS.md gave the target two owners with
# different ideas of what it should contain, so --apply wrote it and then linked it away, and the
# next --check went red for ever (caught by scripts/tests/test-codex-sync.sh, 5.9.2026).
STUB_SRC="$CLAUDE_HOME/codex/home-AGENTS.md"
if [ "$(cat "$STUB_SRC" 2>/dev/null)" = "$STUB_TEXT" ]; then ok "the home stub text"
else note "codex/home-AGENTS.md does not hold the stub text"
  if [ "$MODE" = "--apply" ]; then
    if ! backup "$STUB_SRC"; then cannot "$STUB_SRC: backup failed, not rewritten"
    elif mkdir -p "$(dirname "$STUB_SRC")" && printf '%s\n' "$STUB_TEXT" > "$STUB_SRC" \
         && [ "$(cat "$STUB_SRC")" = "$STUB_TEXT" ]; then did "codex/home-AGENTS.md"
    else cannot "$STUB_SRC could not be written"; fi
  fi
fi

# ---- 3. skills ---------------------------------------------------------------------------------
echo "── skills ──"
for src in "$CLAUDE_HOME"/skills/*/; do
  name=$(basename "$src")
  dst="$AGENTS_DIR/skills/$name"
  want="$CLAUDE_HOME/skills/$name"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$want" ]; then ok "skill $name"
  elif [ -L "$want" ] && [ -d "$dst" ] && [ ! -L "$dst" ] \
       && [ "$(cd "$want" 2>/dev/null && pwd -P)" = "$(cd "$dst" && pwd -P)" ]; then
    # The arrow points the other way on a Linux host: `npx skills` installs into ~/.agents/skills
    # and ~/.claude/skills/<name> links there. Same single source, Codex reads it natively.
    ok "skill $name (source in ~/.agents, Claude links to it)"
  elif [ -e "$dst" ] && [ ! -L "$dst" ]; then
    note "skill $name is a COPY, not a link — the importer has taken this target back"
    [ "$MODE" = "--apply" ] && replace_with_link "$dst" "$want" "skill $name relinked"
  else
    note "skill $name is not linked"
    [ "$MODE" = "--apply" ] && replace_with_link "$dst" "$want" "skill $name linked"
  fi
done
for dst in "$AGENTS_DIR"/skills/*/; do
  name=$(basename "$dst")
  [ -d "$CLAUDE_HOME/skills/$name" ] || cannot "skill $name exists in Codex but not in the Claude source"
done

# ---- 4. hooks -----------------------------------------------------------------------------------
echo "── hooks ──"
# codex/hooks.json is a RENDERING of codex/hooks.template.json: the template carries
# __CODEX_HOME__ where Codex needs an absolute path. The rendered file is what ~/.codex/hooks.json
# links to, so a stale rendering is drift and --apply rewrites it. The comparison guards the
# write, so an unchanged rendering keeps its mtime and the hook trust hashes.
HOOKS_TPL="$CLAUDE_HOME/codex/hooks.template.json"
if [ -f "$HOOKS_TPL" ]; then
  if ! RENDERED_HASH=$(render_tpl "$HOOKS_TPL" | sha256_stream) || [ -z "$RENDERED_HASH" ] \
     || ! render_tpl "$HOOKS_TPL" >/dev/null; then
    cannot "codex/hooks.template.json could not be rendered — hooks.json left untouched"
  elif [ -f "$CLAUDE_HOME/codex/hooks.json" ] && [ "$(sha256 "$CLAUDE_HOME/codex/hooks.json")" = "$RENDERED_HASH" ]; then
    ok "codex/hooks.json matches its template"
  else
    note "codex/hooks.json is not the rendering of codex/hooks.template.json"
    if [ "$MODE" = "--apply" ]; then
      if render_tpl "$HOOKS_TPL" > "$CLAUDE_HOME/codex/hooks.json.tmp" \
         && [ "$(sha256 "$CLAUDE_HOME/codex/hooks.json.tmp")" = "$RENDERED_HASH" ] \
         && mv "$CLAUDE_HOME/codex/hooks.json.tmp" "$CLAUDE_HOME/codex/hooks.json"; then
        did "codex/hooks.json rendered from the template"
      else rm -f "$CLAUDE_HOME/codex/hooks.json.tmp"; cannot "codex/hooks.json could not be rendered"; fi
    fi
  fi
else
  note "codex/hooks.template.json missing — codex/hooks.json is used as-is"
fi
# Read the hook list from the REPO copy when it exists, for the same reason as DELTA above: on a
# fresh machine the ~/.codex/hooks.json symlink is created by section 4b, which runs AFTER this
# one, so the first --apply linked no hook at all (measured 12.9.2026 on a Linux host).
HOOKS_JSON="$CLAUDE_HOME/codex/hooks.json"; [ -f "$HOOKS_JSON" ] || HOOKS_JSON="$CODEX_HOME/hooks.json"
if [ -f "$HOOKS_JSON" ]; then
  while read -r name; do
    [ -z "$name" ] && continue
    dst="$CODEX_HOME/hooks/$name"
    want="$CLAUDE_HOME/hooks/$name"
    if [ ! -f "$want" ]; then cannot "hooks.json names $name but $want does not exist"; continue; fi
    if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$want" ]; then ok "hook $name"
    else
      note "hook $name is not linked to the Claude source"
      [ "$MODE" = "--apply" ] && replace_with_link "$dst" "$want" "hook $name linked"
    fi
  done < <(HOOKS_JSON="$HOOKS_JSON" python3 -c "
import json,os,re
d=json.load(open(os.environ['HOOKS_JSON']))
for g in d['hooks'].get('PreToolUse',[]):
    for h in g['hooks']:
        m=re.search(r'/hooks/([A-Za-z0-9_.-]+\.sh)', h.get('command',''))
        if m: print(m.group(1))
" | sort -u)
fi

# ---- 4b. the hand-written Codex files that live in this repo ------------------------------------
echo "── codex config in the repo ──"
link_to() { # link_to <target> <repo-relative source>
  dst="$1"; want="$CLAUDE_HOME/$2"
  if [ ! -e "$want" ]; then cannot "missing in the repo: $2"; return; fi
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$want" ]; then ok "$(basename "$dst")"; return; fi
  note "$dst is not linked to $2"
  [ "$MODE" = "--apply" ] && replace_with_link "$dst" "$want" "$(basename "$dst") linked"
}
link_to "$CODEX_HOME/AGENTS.codex.md"     codex/AGENTS.codex.md
link_to "$CODEX_HOME/hooks.json"          codex/hooks.json
for rf in "$CLAUDE_HOME"/codex/rules/*.rules; do
  [ -f "$rf" ] || continue
  link_to "$CODEX_HOME/rules/$(basename "$rf")" "codex/rules/$(basename "$rf")"
done
link_to "$STUB"                           codex/home-AGENTS.md

# safe-bin is COPIED, not linked, and that is the one deliberate exception.
# The permission profile grants ~/.codex read access so a sandboxed command cannot rewrite the
# wrappers that authorise work outside the sandbox. A symlink would move them under ~/.claude,
# which sits inside the home workspace and is writable when the cwd is ~ — that is exactly the
# escalation the profile exists to prevent. So the repo holds the canonical copy, this script
# writes it, and --check compares by hash.
# A `*.template` wrapper is RENDERED (placeholders -> this machine's values, see render_tpl) and
# compared by content; the wrapper pins HOME, USER and the projects directory as constants on
# purpose, so those cannot be read from the environment at run time.
for f in "$CLAUDE_HOME"/codex/safe-bin/*; do
  [ -f "$f" ] || continue
  b=$(basename "$f")
  case "$b" in
    *.template)
      b="${b%.template}"; dst="$CODEX_HOME/safe-bin/$b"
      if ! WANT_HASH=$(render_tpl "$f" | sha256_stream) || [ -z "$WANT_HASH" ] || ! render_tpl "$f" >/dev/null; then
        cannot "safe-bin/$b: template could not be rendered — target left untouched"; continue
      fi
      if [ -f "$dst" ] && [ "$(sha256 "$dst")" = "$WANT_HASH" ]; then ok "safe-bin/$b (rendered)"
      else
        note "safe-bin/$b differs from the rendering of its template"
        if [ "$MODE" = "--apply" ]; then
          if ! backup "$dst"; then cannot "safe-bin/$b: backup failed, target left untouched"
          elif render_tpl "$f" > "$dst.tmp" && chmod 755 "$dst.tmp" \
               && [ "$(sha256 "$dst.tmp")" = "$WANT_HASH" ] \
               && { case "$b" in *.sh) bash -n "$dst.tmp" ;; *) true ;; esac; } \
               && mv "$dst.tmp" "$dst"; then did "safe-bin/$b rendered from its template"
          else rm -f "$dst.tmp"; cannot "safe-bin/$b could not be rendered"; fi
        fi
      fi
      ;;
    *)
      dst="$CODEX_HOME/safe-bin/$b"
      if [ -f "$dst" ] && [ "$(sha256 "$f")" = "$(sha256 "$dst")" ]; then
        ok "safe-bin/$b"
      else
        note "safe-bin/$b differs from the repo copy"
        if [ "$MODE" = "--apply" ]; then
          if ! backup "$dst"; then cannot "safe-bin/$b: backup failed, target left untouched"
          elif cp -a "$f" "$dst" && cmp -s "$f" "$dst"; then did "safe-bin/$b restored from the repo"
          else cannot "safe-bin/$b could not be restored"; fi
        fi
      fi
      ;;
  esac
done

# ---- 4c. config.toml invariants — asserted rather than copied -----------------------------------------
echo "── codex permissions ──"
CFG="$CODEX_HOME/config.toml"
# A permission change is not for this script to undo — but it must not pass as drift that was
# handled either. It is unrepairable-by-design, so it lands in `failed` and --apply exits 1.
assert_cfg() { # assert_cfg <literal> <label>
  if grep -qF "$1" "$CFG" 2>/dev/null; then ok "$2"; else cannot "config.toml no longer says: $2"; fi
}
if [ ! -f "$CFG" ]; then
  # A missing file is one finding ("not configured yet"), not eight "no longer says" lines.
  cannot "$CFG is missing — run Codex once and configure it; codex-sync does not create the app-owned config.toml"
  assert_cfg() { :; }
fi
# The profile NAME is machine-specific (codex/local.env CS_CODEX_PROFILE); without one the
# assertion is skipped and says so, because "no profile configured" is a finding for the reader.
if [ -n "${CS_CODEX_PROFILE:-}" ]; then
  assert_cfg "default_permissions = \"$CS_CODEX_PROFILE\""        "permission profile $CS_CODEX_PROFILE"
else
  echo "  skip   CS_CODEX_PROFILE is not set in codex/local.env — the permission-profile assertion did not run"
fi
assert_cfg 'approval_policy = "on-request"'                      'approvals on request'
assert_cfg 'approvals_reviewer = "auto_review"'                  'auto_review reviewer'
assert_cfg "\"$CS_HOME/.private_keys\" = \"deny\""        'private keys denied'
assert_cfg "\"$CS_HOME/.ssh\" = \"deny\""                 'ssh denied'
assert_cfg "\"$CS_HOME/.claude/scripts\" = \"read\""      'helper scripts readable'
assert_cfg "\"$CS_HOME/.claude/skills\" = \"read\""       'skills readable'
assert_cfg "\"$CS_HOME/.claude/hooks\" = \"read\""        'hooks readable'
# The native importer is a ChatGPT desktop feature; a config without a [desktop] section (the
# CLI-only install on a Linux host) has no importer to keep on (measured 12.9.2026 there).
if grep -q '^\[desktop\]' "$CFG" 2>/dev/null; then
  assert_cfg 'external-agent-import-sync-enabled = true'           'native import still on'
fi

# Every hooks.json entry has to be TRUSTED or it is skipped in silence.
UNTRUSTED=$(CODEX_HOME="$CODEX_HOME" python3 - <<'PY'
import json, os, re
h = os.path.join(os.environ["CODEX_HOME"], "hooks.json")
try:
    c = open(os.path.join(os.environ["CODEX_HOME"], "config.toml")).read()
except OSError:
    c = ""
try:
    d = json.load(open(h))
except Exception:
    print("hooks.json unreadable"); raise SystemExit
out = []
for gi, g in enumerate(d.get("hooks", {}).get("PreToolUse", [])):
    for hi, e in enumerate(g["hooks"]):
        if f'hooks.json:pre_tool_use:{gi}:{hi}"' not in c:
            m = re.search(r"/hooks/([A-Za-z0-9_.-]+)\.sh", e.get("command", ""))
            out.append(m.group(1) if m else f"{gi}:{hi}")
print(" ".join(out))
PY
)
if [ "$UNTRUSTED" = "hooks.json unreadable" ]; then cannot "$CODEX_HOME/hooks.json is missing or not JSON — the trust check could not run"
elif [ -n "$UNTRUSTED" ]; then cannot "hooks configured but NOT trusted, so silently skipped: $UNTRUSTED"
else ok "all hooks.json entries trusted"; fi

# ---- 4d. Agy — a restore copy, compared rather than written back ------------------------------------
echo "── agy ──"
agy_cmp() { # agy_cmp <live path> <repo-relative copy> — reports, does not write
  if [ ! -f "$1" ]; then note "agy: $1 is missing"; return; fi
  if cmp -s "$1" "$CLAUDE_HOME/$2"; then ok "agy $(basename "$2")"
  else advise "agy $(basename "$2") differs from the repo copy — refresh it deliberately, the app owns that file"; fi
}
if [ -d "$CLAUDE_HOME/agy" ]; then
  agy_cmp "$CS_HOME/.gemini/settings.json"                      agy/gemini-settings.json
  agy_cmp "$CS_HOME/.gemini/antigravity-cli/settings.json"      agy/antigravity-cli-settings.json
else
  ok "agy: no restore copy in this ~/.claude, nothing to compare"
fi

# ---- 4e. project checkouts — inspected, not written ---------------------------------------------------
echo "── projects ──"
# The checkouts to inspect come from codex/local.env (CS_PROJECTS, space-separated); with an
# empty value this section inspects nothing and says so.
: "${CS_PROJECTS:=}"
[ -n "$CS_PROJECTS" ] || ok "CS_PROJECTS is empty — no project checkout inspected"
for repo in $CS_PROJECTS; do
  [ -d "$repo/.git" ] || continue
  name=$(basename "$repo")

  if [ ! -e "$repo/AGENTS.md" ]; then
    advise "$name has no AGENTS.md, so Codex loads no project instructions there"
  else
    ok "$name AGENTS.md"
  fi

  # Skills a project ships for Codex must resolve; a dangling one lists in the catalogue and
  # fails to open.
  if [ -d "$repo/.agents/skills" ]; then
    bad=""
    for e in "$repo"/.agents/skills/*; do
      # -e is FALSE for a dangling symlink, so testing it first skipped exactly the entry this
      # loop exists to find (reproduced 5.9.2026). -L keeps the broken ones in.
      [ -e "$e" ] || [ -L "$e" ] || continue
      if [ ! -d "$e" ]; then bad="$bad $(basename "$e")"
      elif [ ! -f "$e/SKILL.md" ]; then bad="$bad $(basename "$e")(no SKILL.md)"; fi
    done
    [ -n "$bad" ] && advise "$name has unresolvable project skills:$bad"
  fi

  # Is the checkout carrying the agent configuration that is already on the remote? Comparing
  # these paths alone keep the answer about this script's concern, not about the project's code.
  if git -C "$repo" rev-parse --verify -q origin/main >/dev/null 2>&1; then
    behind=$(git -C "$repo" diff --name-only HEAD origin/main -- AGENTS.md .agents 2>/dev/null | head -5)
    if [ -n "$behind" ]; then
      advise "$name working tree differs from origin/main on the agent config: $(echo $behind | tr '\n' ' ')"
    else
      ok "$name agent config matches origin/main"
    fi
  fi
done

# ---- 5. helper references named by the skills ----------------------------------------------------
echo "── helper references ──"
missing=$(grep -rhoE "~/\.claude/scripts/[A-Za-z0-9_.-]+" "$CLAUDE_HOME/skills" "$RULEBOOK" 2>/dev/null | sort -u | while read -r r; do
  p="${r/#\~/$HOME}"; [ -e "$p" ] || echo "$r"; done)
if [ -n "$missing" ]; then cannot "skills name helpers that do not exist: $(echo $missing)"; else ok "every ~/.claude/scripts/* reference resolves"; fi

badcase=$(grep -rlE "\.Codex/" "$CLAUDE_HOME/skills" "$AGENTS_DIR/skills" 2>/dev/null | sort -u)
if [ -n "$badcase" ]; then cannot "importer-rewritten .Codex/ paths present in: $(echo $badcase)"; else ok "no rewritten .Codex/ paths"; fi

# ---- 6. optional: the hook fixture suite ----------------------------------------------------------
if [ "$RUN_TESTS" = "1" ]; then
  echo "── hook fixtures ──"
  if out=$(bash "$CLAUDE_HOME/hooks/tests/test-hooks.sh" 2>&1); then ok "$(echo "$out" | tail -1 | tr -s ' ')"
  else note "hook fixtures FAILED: $(echo "$out" | grep '❌' | head -3 | tr '\n' ' ')"; fi
fi

# ---- report ----------------------------------------------------------------------------------------
mkdir -p "$(dirname "$REPORT")"
# Order: <report> <mode> <repaired count> <failed count> <repaired…> -- <failed…> -- <drift…>
if ! CODEX_HOME="$CODEX_HOME" python3 - "$REPORT" "$MODE" "${#repaired[@]}" "${#failed[@]}" \
     "${repaired[@]:-}" "--" "${failed[@]:-}" "--" "${advisory[@]:-}" "--" "${drift[@]:-}" <<'PY'
import json, os, sys, time
report, mode = sys.argv[1], sys.argv[2]
nr, nf = int(sys.argv[3]), int(sys.argv[4])
rest = sys.argv[5:]
def take(seq):
    out = []
    while seq and seq[0] != "--":
        if seq[0]:
            out.append(seq[0])
        seq.pop(0)
    if seq:
        seq.pop(0)
    return out
repaired = take(rest); failed = take(rest); advisory = take(rest)
items = [d for d in rest if d]

# When the native importer last ran. Recording it next to the drift makes the two attributable:
# drift that appears with a NEW timestamp is the importer taking a target back, drift with the
# same timestamp is something else (a hand edit, a moved file).
last_import = None
try:
    g = json.load(open(os.path.join(os.environ.get("CODEX_HOME", os.path.expanduser("~/.codex")), ".codex-global-state.json")))
    st = g.get("electron-persisted-atom-state", {}).get("external-agent-import-sync-state", {})
    ms = st.get("lastSyncStartedAtMs")
    if ms:
        last_import = time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime(ms / 1000))
except Exception:
    pass

json.dump({"checked_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "mode": mode,
           "native_import_last_run": last_import,
           "drift_count": len(items), "drift": items,
           "repaired_count": nr, "repaired": repaired,
           "unrepaired_count": nf, "unrepaired": failed,
           "needs_a_human_count": len(advisory), "needs_a_human": advisory},
          open(report, "w"), indent=1, ensure_ascii=False)
PY
then
  # A report that cannot be written is the instrument going dark, and the previous file would sit
  # there looking current. Say so instead.
  cannot "the JSON report at $REPORT could not be written"
fi

echo
NF=${#failed[@]}; NR=${#repaired[@]}; ND=${#drift[@]}

# Structural guard, not a per-call-site promise: a finding that was reported and NOT repaired keeps
# --apply from returning green, whoever adds the next check and whatever bucket they choose. The
# version before this one relied on each site picking the right one, and a permission change that
# called note() alone came out as "in sync" (reproduced 5.9.2026).
REMAINING=$(( ND - NR ))
[ "$REMAINING" -lt 0 ] && REMAINING=0

if [ "$MODE" = "--apply" ]; then
  # A repair that was made and a repair that could not be made are different outcomes and get
  # different exit codes. Saying "repaired" for both is what let a refused write report success.
  if [ "$NF" -gt 0 ] || [ "$REMAINING" -gt 0 ]; then
    notify "codex-sync: needs a human" "$NF item(s) could NOT be repaired — see codex-sync-report.json"
    echo "repaired $NR item(s); $NF unrepairable, $REMAINING left unhandled — report in $REPORT" >&2
    exit 1
  fi
  if [ "$NR" -gt 0 ]; then
    # Drift that was repaired is still a signal: these targets have one other plausible writer,
    # and repairing in silence would hide the day the importer starts taking them back.
    notify "codex-sync: Codex config had drifted" "$NR item(s) repaired — see codex-sync-report.json"
    echo "repaired $NR item(s) — report in $REPORT"
    exit 0
  fi
  if [ "${#advisory[@]}" -gt 0 ]; then
    # Nothing to repair and nothing to notify: these need a person, and saying "in sync" over
    # them would be the false green this whole script exists to prevent.
    echo "nothing to repair here; ${#advisory[@]} item(s) need a human — report in $REPORT"
    exit 0
  fi
  echo "in sync — report in $REPORT"; exit 0
fi

if [ "$NF" -gt 0 ] || [ "$ND" -gt 0 ] || [ "${#advisory[@]}" -gt 0 ]; then
  echo "drift: $ND item(s), $NF unrepairable, ${#advisory[@]} need a human — report in $REPORT"; exit 1
fi
echo "in sync — report in $REPORT"
